
clear all
%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\jrenaud\Desktop\Joe Docs\Documents\Projects &
%    Research\ProgrammingRepositories\ResearchCode\Exoplanet Occurance
%    Project\ExoplanetProjectSprin2014\Exoplanets by year\2013.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/04/13 18:14:07

%% Initialize variables.
filename = 'C:\Users\jrenaud\Desktop\Joe Docs\Documents\Projects & Research\ProgrammingRepositories\ResearchCode\Exoplanet Occurance Project\ExoplanetProjectSprin2014\Exoplanets by year\2013.csv';
delimiter = ',';
startRow = 14;
filename2 = 'C:\Users\jrenaud\Desktop\Joe Docs\Documents\Projects & Research\ProgrammingRepositories\ResearchCode\Exoplanet Occurance Project\ExoplanetProjectSprin2014\Exoplanets by year\2014.csv';
delimiter2 = ',';
startRow2 = 11;
%% Format string for each line of text:
formatSpec = '%*s%f%*s%*s%*s%f%[^\n\r]';
formatSpec2 = '%*s%f%*s%*s%*s%f%[^\n\r]';
%% Open the text file.
fileID = fopen(filename,'r');
fileID2 = fopen(filename2,'r');
%% Read columns of data according to format string.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);
dataArray2 = textscan(fileID2, formatSpec2, 'Delimiter', delimiter2, 'EmptyValue' ,NaN,'HeaderLines' ,startRow2-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);
fclose(fileID2);
%% Allocate imported array to column variable names
pl_radj2013 = dataArray{:, 1};
pl_disc2013 = dataArray{:, 2};
pl_radj2014 = dataArray2{:, 1};
pl_disc2014 = dataArray2{:, 2};
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
clearvars filename2 delimiter2 startRow2 formatSpec2 fileID2 dataArray2;

figure(1)
hist(pl_disc2014,max(pl_disc2014)-min(pl_disc2014))
title('Number of Exoplanets discoverd by year')
xlabel('Year')
ylabel('Discoveries')
r2013 = [];
count13 = 1;
r2014 = [];
count14 = 1;
r2012 = [];
count12 = 1;
for i = 1:length(pl_disc2014)
    if pl_disc2014(i) == 2014
        r2014(count14)=pl_radj2014(i);
        count14 = count14 + 1;
    elseif pl_disc2014(i) == 2012
        r2012(count12)=pl_radj2014(i);
        count12 = count12 + 1;
    elseif pl_disc2014(i) == 2013
        r2013(count13)=pl_radj2014(i);
        count13 = count13 + 1;
    end
end
r2012(isnan(r2012))=[];
r2013(isnan(r2013))=[];
r2014(isnan(r2014))=[];
figure(2)
subplot(1,3,1)
hist(r2012,ceil((max(r2012)-min(r2012))/(3.5*length(r2012)^(-1/3)*std(r2012))))
subplot(1,3,2)
hist(r2013,ceil((max(r2013)-min(r2013))/(3.5*length(r2013)^(-1/3)*std(r2013))))
subplot(1,3,3)
hist(r2014,ceil((max(r2014)-min(r2014))/(3.5*length(r2014)^(-1/3)*std(r2014))))